import { ThemeProvider } from '@/components/shared';
import type { Metadata } from 'next';

import '../styles/main.css';

export const metadata: Metadata = {
  title: 'stack unboxed',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
