name: Build and Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies using classic bun
      - name: Install Dependencies
        run: |
          npm install -g bun
          bun install

      - name: Format
        run: bun run format:check

      - name: Lint
        run: bun lint

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test

      # # Optional: Cache the build output
      # - name: Cache build output
      #   uses: actions/cache@v4
      #   with:
      #     path: dist
      #     key: ${{ runner.os }}-build-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-
